### ISSUE TITLE
Error when running container

### ISSUE THREAD

**Issue by mhercol** [lightglitch/seekerr#24]
I just pulled the image with portainer and when trying to run the container I get the following error 
standard_init_linux.go:207: exec user process caused "exec format error"
I have just connected an empty volume, and provided PGID, PUID and TZ as env variables. 
Any idea?

**Comment by lightglitch** [comment]
Did you mapped the volume with config folder?
Did you created the config file?

**Comment by mhercol** [comment]
Thanks for looking into this.
I have a volume mounted in /config, and inside that volume I have a file
called seekerr.yaml with the code proposed as sample configuration.
If it is useful, there is no more structure, meaning there is not a log
folder, so I believe the container has not been capable of running.
I'm running it on a RPI 4 with aarch64 via portainer, if it helps.

**Comment by lightglitch** [comment]
I think I found the problem after some research:

"This can happen if you're trying to run an x86 built image on an arm64/aarch64 machine.

You'll need to rebuild the image using the corresponding architecture."

I will check how to build images for x86 and for your architecture.

**Comment by lightglitch** [comment]
I now have builds for amd64 and arm64, pull the update and see if it solves your problem.

**Comment by mhercol** [comment]
Hi

Thanks again for your time.
I am encountering the same issue, but it might be my fault. . I am pulling
stable release, should I try to pull anything different?

**Comment by lightglitch** [comment]
Check the hash of your image against the arm64 version at https://hub.docker.com/r/lightglitch/seekerr/tags?page=1&name=stable to see if you have the correct one.
