### ISSUE TITLE
Help understanding filters

### ISSUE THREAD

**Issue by drsood** [lightglitch/seekerr#31]
Hi
I have been trying to play around with Seekerr settings. 

1. If I remove `      - 'CountRatings < 2 || Runtime < 20 || ImdbVotes < 1000 || Year > Now().Year()'`, I get many more movie matches for radarr. However this error `ERR Adding movie to radarr error="'Quality Profile Id' must be greater than '0'. QualityProfile does not exist " Component=Importer` shows up in the log. Is that filter a must? 

2. What all parameters does quality under radarr accept? Can I use 1080p?
Thank you

**Comment by lightglitch** [comment]
Can you send the configuration with and without that line? Because the radarr error has noting to do with the filter but with the radarr configuration.

**Comment by drsood** [comment]
I had made a mistake in the config file. I figured that out and its working well now.
Sorry and Thanks.
