### ISSUE TITLE
Feat Req: ARMV7 (32bit) docker support

### ISSUE THREAD

**Issue by neo-neo1** [lightglitch/seekerr#32]
Tried pulling Docker image and received error since only ARM64/AMD64 is included. This omits compatibility for Rasp Pi 3B, ODROIDs, and many countless other SBCs. Unless it’s newest and greatest chances are it requires ARMV7L support. 

Please consider adding it, it’ll be greatly appreciated. Thank you!

**Comment by lightglitch** [comment]
Done. You will need to tested them.

**Comment by neo-neo1** [comment]
> Done. You will need to tested them.

Thank you, quick work! ARMV7 image boots upon initial testing. 

Encountered other (non-related?) issues I posted about.
