### ISSUE TITLE
Sample Config File is Not Created

### ISSUE THREAD

**Issue by neo-neo1** [lightglitch/seekerr#33]
**Problem:** Pulled Docker ARMv7 image and during initial container first boot the sample config file is not copied over to the respective location. Verified there is no file in /config

```
panic: Config File "seekerr" Not Found in "[/config]"

goroutine 1 [running]:

github.com/lightglitch/seekerr/cmd.initConfig()

	/go/src/github.com/lightglitch/seekerr/cmd/root.go:92 +0x350

github.com/lightglitch/seekerr/cmd.glob..func1(0x9cbd40, 0xab763c, 0x0, 0x0)

	/go/src/github.com/lightglitch/seekerr/cmd/cron.go:40 +0x14

github.com/spf13/cobra.(*Command).execute(0x9cbd40, 0xab763c, 0x0, 0x0, 0x9cbd40, 0xab763c)

	/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:849 +0x3a4

github.com/spf13/cobra.(*Command).ExecuteC(0x9cbe88, 0x0, 0x1, 0x1)

	/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:974 +0x280

github.com/spf13/cobra.(*Command).Execute(...)

	/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:902

github.com/lightglitch/seekerr/cmd.Execute()

	/go/src/github.com/lightglitch/seekerr/cmd/root.go:50 +0x20

main.main()

	/go/src/github.com/lightglitch/seekerr/main.go:27 +0x14

```

**Testing and Troubleshooting:** I manually created `seeker.yaml` file and copied contents of `seekerr.sample.yaml` into it and it started successfully. 

```
2:37AM INF start
2:37AM INF schedule 0=now 1=2022-02-12T21:37:21.680945865-05:00 2=entry 3=1 4=next 5=2022-02-12T22:00:00-05:00
```

**Comment by lightglitch** [comment]
As you can see here https://github.com/lightglitch/seekerr#docker you will need to create the file manually.

**Comment by neo-neo1** [comment]
> As you can see here https://github.com/lightglitch/seekerr#docker you will need to create the file manually.

As you can see here your [Dockerfile](https://github.com/lightglitch/seekerr/blob/master/Dockerfile) should copy it over. No reason to manually do so.

```
RUN mkdir /config
COPY --from=build /go/src/github.com/lightglitch/seekerr/config/seekerr.sample.yaml /config/seekerr.sample.yaml
```
  Issue closed prematurely. Thanks

**Comment by lightglitch** [comment]
It only copies the sample. It doesn't create the file `seekerr.yaml` that is necessary to run the docker, the exception was because that file didn't exist. The `seekerr.yaml` needs to be created manually like it says in the documentation.
