### ISSUE TITLE
Tag Support

### ISSUE THREAD

**Issue by hackmonker** [lightglitch/seekerr#35]
I use tags a lot so really hope you would support tags in case sonarr support is added. rn I use mediarr for sonarr but it does not support tags so really hope you support it.

Also is this supported in exclude?

'"animation" in Genres || "anime" in Genres'

**Comment by hackmonker** [comment]
Ah I just saw it is only filtering based on ratings. hope genre and other filters like ratings are also supported in future

**Comment by lightglitch** [comment]
I think I can add new filtering options, I will check what can we add

**Comment by neo-neo1** [comment]
Tag support would indeed be useful to have. Thanks

**Comment by lightglitch** [comment]
Actually we already support `Genre` and `Language` in the rules. They are both a list of tags based on the OMDB information.
And you can use it like:
```
'"Comedy" in Genre && "Animation" not in Genre'
```
The case is the same for Language
```
'"English" in Language
```

**Comment by neo-neo1** [comment]
> Actually we already support `Genre` and `Language` in the rules. They are both a list of tags based on the OMDB information. And you can use it like:
> 
> ```
> '"Comedy" in Genre && "Animation" not in Genre'
> ```
> 
> The case is the same for Language
> 
> ```
> '"English" in Language
> ```

Nice to know. Is there a complete listing of syntax and usable options? I don’t see a mention of this in the readme  and now I’m wondering what else I’m missing and unaware of. Thanks!

**Comment by lightglitch** [comment]
The syntax to use for rules is in the documentation of the engine that we use: github.com/antonmedv/expr

The variables that you can use are in the `ListItem` definition: https://github.com/lightglitch/seekerr/blob/1c189faf0d86d5e36fefc777d1a8f4a692a5df4f/provider/provider.go#L46

Don't know if this a bit to technical for you but I can improve the docs later.
